version: '3.7'
services:
  postgres:
    image: postgres:12.2
    volumes:
      # - pg_data:/var/lib/postgresql/data
      - ${PWD}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=sweepstakes
      - POSTGRES_USER=sweepstakes
      - POSTGRES_PASSWORD=secret
    networks:
      - backend
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready --dbname=sweepstakes --user=sweepstakes']
      interval: 5s
      timeout: 4s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      # - pgadmin_data:/var/lib/pgadmin
      - ${PWD}/servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sweepstakes.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    networks:
      - backend
    ports:
      - 80:80

  mock_api_server:
    image: danielgtaylor/apisprout
    command: /api.yaml
    volumes:
      - ${PWD}/openapi.yaml:/api.yaml
    networks:
      - backend
    ports:
      - 8000:8000

networks:
  backend:
    driver: bridge
# volumes:
# pg_data:
# pgadmin_data:
