openapi: 3.0.3

info:
  title: Sweepstakes API
  description: APIs for the Sweepstakes backend
  version: 0.0.1

servers:
  - url: http://localhost/v1
    description: local development server

paths:
  /tournaments/{tournamentId}/fixtures/{fixtureId}:
    get:
      summary: Returns a fixture for a tournament.
      parameters:
        - $ref: '#/components/parameters/tournamentIdParam'
        - $ref: '#/components/parameters/fixtureIdParam'
      responses:
        '200': # status code
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fixture'
              example:
                id: 4
                tournament_name: UEFA EURO 2020
                home_team: BEL
                away_team: ITA
                kickoff: 12-06-2020
                home_goals: 1
                away_goals: 0
                home_penalties:
                away_penalties:
                group_stage: true

  /tournaments/{tournamentId}/fixtures:
    get:
      summary: Returns a list of fixtures for a tournament.
      parameters:
        - $ref: '#/components/parameters/tournamentIdParam'
      responses:
        '200': # status code
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fixtures'
              example:
                - id: 4
                  tournament_name: UEFA EURO 2020
                  home_team: BEL
                  away_team: ITA
                  kickoff: 12-06-2020
                  home_goals: 1
                  away_goals: 0
                  home_penalties:
                  away_penalties:
                  group_stage: true
                - id: 5
                  tournament_name: UEFA EURO 2020
                  home_team: GER
                  away_team: NLD
                  kickoff: 13-06-2020
                  home_goals: 1
                  away_goals: 3
                  home_penalties:
                  away_penalties:
                  group_stage: true

components:
  #-------------------------------
  # Reusable schemas (data models)
  #-------------------------------
  schemas:
    Fixture: # Can be referenced as '#/components/schemas/Fixture'
      type: object
      properties:
        id:
          type: integer
        tournament_name:
          type: string
        home_team:
          type: string
        away_team:
          type: string
        kickoff:
          type: string
        home_goals:
          type: integer
        away_goals:
          type: integer
        home_penalties:
          type: integer
        away_penalties:
          type: integer
        group_stage:
          type: boolean
        # fixture_data:
    Fixtures: # Can be referenced as '#/components/schemas/Fixtures'
      type: array
      items:
        $ref: '#/components/schemas/Fixtures'

  #-------------------------------
  # Reusable operation parameters
  #-------------------------------
  parameters:
    tournamentIdParam: # Can be referenced via '#/components/parameters/tournamentIdParam'
      name: tournamentId
      in: path
      description: Tournament Identifier for which you want to see the fixtures
      required: true
      schema:
        type: integer
        minimum: 0

    fixtureIdParam: # Can be referenced via '#/components/parameters/fixtureIdParam'
      name: fixtureId
      in: path
      description: Fixture Identifier of Fixture you want to retrieve
      required: true
      schema:
        type: integer
        minimum: 0
