version: "3.8"
services:
  postgres:
    build:
      context: .
    # image: postgres:13.2
    # volumes:
    # - pg_data:/var/lib/postgresql/data
    # - ${PWD}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=sweepstakes
      - POSTGRES_USER=sweepstakes
      - POSTGRES_PASSWORD=secret
    networks:
      - sweepstakes-backend
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=sweepstakes --user=sweepstakes"]
      interval: 5s
      timeout: 4s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:5.0
    volumes:
      # - pgadmin_data:/var/lib/pgadmin
      - ${PWD}/servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sweepstakes.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    networks:
      - sweepstakes-backend
    ports:
      - 80:80

  mock_api_server:
    image: stoplight/prism:4
    command: mock -p 4010 --host 0.0.0.0 /api.yaml
    volumes:
      - ${PWD}/openapi.yaml:/api.yaml
    networks:
      - sweepstakes-backend
    ports:
      - 4010:4010

networks:
  sweepstakes-backend:
    name: sweepstakes-backend
# volumes:
# pg_data:
# pgadmin_data:
